// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS18nMwhFhR1c59lCoIiPdsq31_tvgUzc',
    appId: '1:628194975832:web:7a3a6ba610ab7a4affaa2d',
    messagingSenderId: '628194975832',
    projectId: 'fir-messaging-fcm-bf0db',
    authDomain: 'fir-messaging-fcm-bf0db.firebaseapp.com',
    storageBucket: 'fir-messaging-fcm-bf0db.appspot.com',
    measurementId: 'G-RCY3EK1CL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbhLyIRp2Hg5dU-xRkUDx-cy0AtFFIhkk',
    appId: '1:628194975832:android:1730de7f504051ebffaa2d',
    messagingSenderId: '628194975832',
    projectId: 'fir-messaging-fcm-bf0db',
    storageBucket: 'fir-messaging-fcm-bf0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKy35i4ZOF-tu6lwxijzDsqtWdtSwZkGQ',
    appId: '1:628194975832:ios:d1ba7a8a19e96ea3ffaa2d',
    messagingSenderId: '628194975832',
    projectId: 'fir-messaging-fcm-bf0db',
    storageBucket: 'fir-messaging-fcm-bf0db.appspot.com',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKy35i4ZOF-tu6lwxijzDsqtWdtSwZkGQ',
    appId: '1:628194975832:ios:d1ba7a8a19e96ea3ffaa2d',
    messagingSenderId: '628194975832',
    projectId: 'fir-messaging-fcm-bf0db',
    storageBucket: 'fir-messaging-fcm-bf0db.appspot.com',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS18nMwhFhR1c59lCoIiPdsq31_tvgUzc',
    appId: '1:628194975832:web:1990d9681eeb630effaa2d',
    messagingSenderId: '628194975832',
    projectId: 'fir-messaging-fcm-bf0db',
    authDomain: 'fir-messaging-fcm-bf0db.firebaseapp.com',
    storageBucket: 'fir-messaging-fcm-bf0db.appspot.com',
    measurementId: 'G-7QE33PD7PL',
  );
}
